# Pre-commit hooks configuration

# Hook repositories and versions
repos:
  # Repository: pre-commit hooks by pre-commit organization
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Hook: detect-private-key
      - id: detect-private-key

      # Hook: detect-aws-credentials
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]  # Additional arguments for the hook

      # Hook: trailing-whitespace
      - id: trailing-whitespace

      # Hook: double-quote-string-fixer
      - id: double-quote-string-fixer

      # Hook: end-of-file-fixer
      - id: end-of-file-fixer

      # Hook: check-case-conflict
      - id: check-case-conflict

      # Hook: check-yaml
      - id: check-yaml

      # Hook: name-tests-test
      - id: name-tests-test
        args: ['--django']  # Additional arguments for the hook

      # Hook: check-added-large-files
      - id: check-added-large-files
        args: ['--maxkb=2048']  # Additional arguments for the hook

      # Hook: debug-statements
      - id: debug-statements

  # Repository: pydocstyle
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      # Hook: pydocstyle
      - id: pydocstyle

  # Repository: autopep8 (code formatting)
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
      # Hook: autopep8
      - id: autopep8
        args: [--aggressive, --in-place]  # Additional arguments for the hook

  # Repository: isort (import sorting)
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      # Hook: isort
      - id: isort
        args: [--apply, --profile=default]  # Additional arguments for the hook

  # Repository: black (code formatting)
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      # Hook: black
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.11
        args: [--fast]  # Additional arguments for the hook

  # Repository: pycln (code cleaning)
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      # Hook: pycln
      - id: pycln
        args: [--config=pyproject.toml]

  # Repository: flak8 (code formatting)
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      # Hook: flake8
      - id: flake8

  # Repository: reorder-python-imports (code formatting)
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args: [
            --application-directories, '.:src',
            --py38-plus,
            --add-import, 'from __future__ import annotations',
        ]